repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
- repo: https://github.com/f-koehler/conda-hooks
  rev: v0.2.1
  hooks:
    - id: conda-env-store
    - id: conda-env-update
