channels:
- conda-forge
- defaults
dependencies:
- bandit
- black
- flake8
- ipympl
- jedi[version='<0.18']
- jupyter
- jupyterlab
- matplotlib
- mkl
- mypy
- nodejs
- numpy
- pip
- pylint
- python
- pip:
  - qiskit[visualization]
name: jc_vqs
