channels:
- conda-forge
- defaults
dependencies:
- bandit
- black
- flake8
- ipympl
- jedi[version='<0.18']
- jupyter
- jupyterlab
- matplotlib
- mkl
- mypy
- nodejs
- numpy
- pip
- pylint
- python==3.8
- pip:
  - qiskit[visualization]
  - qiskit-aer-gpu
  - jblack
name: jc_vqs
